name: acter_avatar
description: Avatars as used by Acter.global
version: 1.0.4
homepage: https://github.com/acterglobal/acter-avatar

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ">=1.0.5"
  multiavatar: ^0.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
